### ISSUE TITLE
Fail while installing

### ISSUE THREAD

**Issue by szalikdev** [clayrisser/breeze-hacked-cursor-theme#4]
After typing make install this is what i get:

make install
Checking Requirements... DONE
Making Folders... DONE
Generating simple cursor pixmaps... DONE
Generating animated cursor pixmaps... DONE
FAIL: src/config/alias.cursor xcursorgen: PNG error while reading x1/alias.png
FAIL: src/config/all-scroll.cursor xcursorgen: PNG error while reading x1/all-scroll.png
FAIL: src/config/bottom_left_corner.cursor xcursorgen: PNG error while reading x1/bottom_left_corner.png
FAIL: src/config/bottom_right_corner.cursor xcursorgen: PNG error while reading x1/bottom_right_corner.png
FAIL: src/config/bottom_side.cursor xcursorgen: PNG error while reading x1/bottom_side.png
FAIL: src/config/cell.cursor xcursorgen: PNG error while reading x1/cell.png
FAIL: src/config/center_ptr.cursor xcursorgen: PNG error while reading x1/center_ptr.png
FAIL: src/config/color-picker.cursor xcursorgen: PNG error while reading x1/color-picker.png
FAIL: src/config/col-resize.cursor xcursorgen: PNG error while reading x1/col-resize.png
FAIL: src/config/context-menu.cursor xcursorgen: PNG error while reading x1/context-menu.png
FAIL: src/config/copy.cursor xcursorgen: PNG error while reading x1/copy.png
FAIL: src/config/crosshair.cursor xcursorgen: PNG error while reading x1/crosshair.png
FAIL: src/config/default.cursor xcursorgen: PNG error while reading x1/default.png
FAIL: src/config/dnd-move.cursor xcursorgen: PNG error while reading x1/dnd-move.png
FAIL: src/config/dnd-no-drop.cursor xcursorgen: PNG error while reading x1/dnd-no-drop.png
FAIL: src/config/down-arrow.cursor xcursorgen: PNG error while reading x1/down-arrow.png
FAIL: src/config/draft.cursor xcursorgen: PNG error while reading x1/draft.png
FAIL: src/config/fleur.cursor xcursorgen: PNG error while reading x1/fleur.png
FAIL: src/config/help.cursor xcursorgen: PNG error while reading x1/help.png
FAIL: src/config/left-arrow.cursor xcursorgen: PNG error while reading x1/left-arrow.png
FAIL: src/config/left_side.cursor xcursorgen: PNG error while reading x1/left_side.png
FAIL: src/config/no-drop.cursor xcursorgen: PNG error while reading x1/no-drop.png
FAIL: src/config/not-allowed.cursor xcursorgen: PNG error while reading x1/not-allowed.png
FAIL: src/config/openhand.cursor xcursorgen: PNG error while reading x1/openhand.png
FAIL: src/config/pencil.cursor xcursorgen: PNG error while reading x1/pencil.png
FAIL: src/config/pirate.cursor xcursorgen: PNG error while reading x1/pirate.png
FAIL: src/config/pointer.cursor xcursorgen: PNG error while reading x1/pointer.png
FAIL: src/config/progress.cursor xcursorgen: PNG error while reading x1/progress-01.png
FAIL: src/config/right-arrow.cursor xcursorgen: PNG error while reading x1/right-arrow.png
FAIL: src/config/right_ptr.cursor xcursorgen: PNG error while reading x1/right_ptr.png
FAIL: src/config/right_side.cursor xcursorgen: PNG error while reading x1/right_side.png
FAIL: src/config/row-resize.cursor xcursorgen: PNG error while reading x1/row-resize.png
FAIL: src/config/size_bdiag.cursor xcursorgen: PNG error while reading x1/size_bdiag.png
FAIL: src/config/size_fdiag.cursor xcursorgen: PNG error while reading x1/size_fdiag.png
FAIL: src/config/size_hor.cursor xcursorgen: PNG error while reading x1/size_hor.png
FAIL: src/config/size_ver.cursor xcursorgen: PNG error while reading x1/size_ver.png
FAIL: src/config/text.cursor xcursorgen: PNG error while reading x1/text.png
FAIL: src/config/top_left_corner.cursor xcursorgen: PNG error while reading x1/top_left_corner.png
FAIL: src/config/top_right_corner.cursor xcursorgen: PNG error while reading x1/top_right_corner.png
FAIL: src/config/top_side.cursor xcursorgen: PNG error while reading x1/top_side.png
FAIL: src/config/up-arrow.cursor xcursorgen: PNG error while reading x1/up-arrow.png
FAIL: src/config/vertical-text.cursor xcursorgen: PNG error while reading x1/vertical-text.png
FAIL: src/config/wait.cursor xcursorgen: PNG error while reading x1/wait-01.png
FAIL: src/config/wayland-cursor.cursor xcursorgen: PNG error while reading x1/wayland-cursor.png
FAIL: src/config/x-cursor.cursor xcursorgen: PNG error while reading x1/x-cursor.png
FAIL: src/config/zoom-in.cursor xcursorgen: PNG error while reading x1/zoom-in.png
FAIL: src/config/zoom-out.cursor xcursorgen: PNG error while reading x1/zoom-out.png
Generating cursor theme... DONE
Generating shortcuts... DONE
Copying Theme Index... DONE
COMPLETE!
::: BUILD :::
::: INSTALL :::

**Comment by gonthalo** [comment]
Same here, more or less.
"make install" produces the following:
::: BUILD :::
::: INSTALL :::
but just running ./build.sh gives:
Checking Requirements... DONE
Making Folders... DONE
Generating simple cursor pixmaps... DONE
Generating animated cursor pixmaps... DONE
FAIL: src/config/alias.cursor xcursorgen: PNG error while reading x1/alias.png
FAIL: src/config/all-scroll.cursor xcursorgen: PNG error while reading x1/all-scroll.png
FAIL: src/config/bottom_left_corner.cursor xcursorgen: PNG error while reading x1/bottom_left_corner.png
FAIL: src/config/bottom_right_corner.cursor xcursorgen: PNG error while reading x1/bottom_right_corner.png
FAIL: src/config/bottom_side.cursor xcursorgen: PNG error while reading x1/bottom_side.png
FAIL: src/config/cell.cursor xcursorgen: PNG error while reading x1/cell.png
FAIL: src/config/center_ptr.cursor xcursorgen: PNG error while reading x1/center_ptr.png
FAIL: src/config/color-picker.cursor xcursorgen: PNG error while reading x1/color-picker.png
FAIL: src/config/col-resize.cursor xcursorgen: PNG error while reading x1/col-resize.png
FAIL: src/config/context-menu.cursor xcursorgen: PNG error while reading x1/context-menu.png
FAIL: src/config/copy.cursor xcursorgen: PNG error while reading x1/copy.png
FAIL: src/config/crosshair.cursor xcursorgen: PNG error while reading x1/crosshair.png
FAIL: src/config/default.cursor xcursorgen: PNG error while reading x1/default.png
FAIL: src/config/dnd-move.cursor xcursorgen: PNG error while reading x1/dnd-move.png
FAIL: src/config/dnd-no-drop.cursor xcursorgen: PNG error while reading x1/dnd-no-drop.png
FAIL: src/config/down-arrow.cursor xcursorgen: PNG error while reading x1/down-arrow.png
FAIL: src/config/draft.cursor xcursorgen: PNG error while reading x1/draft.png
FAIL: src/config/fleur.cursor xcursorgen: PNG error while reading x1/fleur.png
FAIL: src/config/help.cursor xcursorgen: PNG error while reading x1/help.png
FAIL: src/config/left-arrow.cursor xcursorgen: PNG error while reading x1/left-arrow.png
FAIL: src/config/left_side.cursor xcursorgen: PNG error while reading x1/left_side.png
FAIL: src/config/no-drop.cursor xcursorgen: PNG error while reading x1/no-drop.png
FAIL: src/config/not-allowed.cursor xcursorgen: PNG error while reading x1/not-allowed.png
FAIL: src/config/openhand.cursor xcursorgen: PNG error while reading x1/openhand.png
FAIL: src/config/pencil.cursor xcursorgen: PNG error while reading x1/pencil.png
FAIL: src/config/pirate.cursor xcursorgen: PNG error while reading x1/pirate.png
FAIL: src/config/pointer.cursor xcursorgen: PNG error while reading x1/pointer.png
FAIL: src/config/progress.cursor xcursorgen: PNG error while reading x1/progress-01.png
FAIL: src/config/right-arrow.cursor xcursorgen: PNG error while reading x1/right-arrow.png
FAIL: src/config/right_ptr.cursor xcursorgen: PNG error while reading x1/right_ptr.png
FAIL: src/config/right_side.cursor xcursorgen: PNG error while reading x1/right_side.png
FAIL: src/config/row-resize.cursor xcursorgen: PNG error while reading x1/row-resize.png
FAIL: src/config/size_bdiag.cursor xcursorgen: PNG error while reading x1/size_bdiag.png
FAIL: src/config/size_fdiag.cursor xcursorgen: PNG error while reading x1/size_fdiag.png
FAIL: src/config/size_hor.cursor xcursorgen: PNG error while reading x1/size_hor.png
FAIL: src/config/size_ver.cursor xcursorgen: PNG error while reading x1/size_ver.png
FAIL: src/config/text.cursor xcursorgen: PNG error while reading x1/text.png
FAIL: src/config/top_left_corner.cursor xcursorgen: PNG error while reading x1/top_left_corner.png
FAIL: src/config/top_right_corner.cursor xcursorgen: PNG error while reading x1/top_right_corner.png
FAIL: src/config/top_side.cursor xcursorgen: PNG error while reading x1/top_side.png
FAIL: src/config/up-arrow.cursor xcursorgen: PNG error while reading x1/up-arrow.png
FAIL: src/config/vertical-text.cursor xcursorgen: PNG error while reading x1/vertical-text.png
FAIL: src/config/wait.cursor xcursorgen: PNG error while reading x1/wait-01.png
FAIL: src/config/wayland-cursor.cursor xcursorgen: PNG error while reading x1/wayland-cursor.png
FAIL: src/config/x-cursor.cursor xcursorgen: PNG error while reading x1/x-cursor.png
FAIL: src/config/zoom-in.cursor xcursorgen: PNG error while reading x1/zoom-in.png
FAIL: src/config/zoom-out.cursor xcursorgen: PNG error while reading x1/zoom-out.png
Generating cursor theme... DONE
Generating shortcuts... DONE
Copying Theme Index... DONE
COMPLETE!

I am running mate desktop over ubuntu

**Comment by clayrisser** [comment]
Are you still facing this issue?

**Comment by gonthalo** [comment]
No, I don't think so, I could install it in the end. Don't remember what I changed though :(

**Comment by szalikdev** [comment]
> Are you still facing this issue?

took you long enough 😅

**Comment by clayrisser** [comment]
Yeah, I went through a year hiatus from GitHub, but I'm back!
