### ISSUE TITLE
Color version, black/grey

### ISSUE THREAD

**Issue by nnuel** [clayrisser/breeze-hacked-cursor-theme#5]
Does this include multiple color versions, or is it only the one in the screenshot?

**Comment by clayrisser** [comment]
Only the one in the screenshot, but pull requests with other colors are welcome.

**Comment by eylles** [comment]
i have been working quite in a rather sporadic way on a script to change the color of the cursor.
https://github.com/eylles/breeze-hacked-cursor-theme/blob/oomox-plugin/change_color.sh

currently my progress is halted because i wanted to add a slightly modified version of the cursor theme as an option but haven't got to modifiying the svg yet.

**Comment by nnuel** [comment]
@eylles Would it change color based on light versus dark mode or is it something else that triggers a change. Or would it be to transform a base version into a permanent other base colored-version?

**Comment by eylles** [comment]
@nnuel ehh not really no, the script is rather more primitive to say, if you want mutiple colored version you will have to run the script multiple times with different colors, as it can recieve theme name and path from args -o and -p respectively, the colors can be passed from a file or from shell redirection like so:
```sh
change_color.sh -o my-theme-name -p /path/to/.icons < (echo -e "BG=0E0E0E\nACCENT_BG=34BE5B")
```
you can also just pass a key=value file as last argument to the scrip, which needs to have the vars "BG" and "ACCENT_BG", as for the colors they have to be 6 digit RGB hex color values without the hash symbol "#"

that will do a sed in the svg to change the colors, then will copy the necesary files over a directory in /tmp and proceed to render the cursor with inkscape, once it is done it will export the theme to the specified path with the specified name.

**Comment by clayrisser** [comment]
Just merged the pr for this. Hopefully it helps.
